spring.application.name=motivaid

spring.datasource.url=jdbc:postgresql://dpg-d3thab7diees73di5mk0-a.render.com:5432/motivaid_db?sslmode=require
spring.datasource.username=motivaid_db_user
spring.datasource.password=gyFI1u6jxS0S5PVb9GrzpPKc4gAj1Kgy
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
